// <auto-generated />
using KaniniInvestmentSearchEngineCompanyMarketEssentials.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

#nullable disable

namespace KaniniInvestmentSearchEngineCompanyMarketEssentials.Migrations
{
    [DbContext(typeof(CompanyEssentialsContext))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CompanyEssentialsMicroService.Models.CompanyEssentials", b =>
                {
                    b.Property<int>("EssenID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EssenID"), 1L, 1);

                    b.Property<double>("BookValue")
                        .HasColumnType("float");

                    b.Property<double>("Cash")
                        .HasColumnType("float");

                    b.Property<int>("CompanyID")
                        .HasColumnType("int");

                    b.Property<double>("DivYield")
                        .HasColumnType("float");

                    b.Property<double>("EnterpriceValue")
                        .HasColumnType("float");

                    b.Property<double?>("Eps")
                        .HasColumnType("float");

                    b.Property<double>("MarketCap")
                        .HasColumnType("float");

                    b.Property<double>("NetIncome")
                        .HasColumnType("float");

                    b.Property<double>("NoOfShares")
                        .HasColumnType("float");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<double?>("PriceToBook")
                        .HasColumnType("float");

                    b.Property<double?>("PriceToEarning")
                        .HasColumnType("float");

                    b.Property<double>("PromoterHolding")
                        .HasColumnType("float");

                    b.Property<string>("Sector")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EssenID");

                    b.ToTable("CompanyEssentials");
                });
#pragma warning restore 612, 618
        }
    }
}
